INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,1,1,'macdonalds',30);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,1,2,'Pizza Hut',50);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,1,1,'Shawrma',40);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,2,2,'Fuel',30);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,2,1,'Costco',50);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,2,2,'Shell',20);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,3,1,'Super Store',50);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,3,2,'Shopper Drug Mart',10);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,3,1,'Costco',50);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,2,2,'Shell',20);