INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,1,1,'macdonalds',3000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,1,2,'Pizza Hut',5000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,1,1,'Shawrma',4000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,2,2,'Fuel',3000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,2,1,'Costco',5000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,2,2,'Shell',2000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (1,3,1,'Super Store',5000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (2,3,2,'Shopper Drug Mart',1000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,3,1,'Costco',5000);
INSERT INTO transactions (category_id, account_id,transaction_type_id, payee,amount_cents ) VALUES (3,2,2,'Shell',2000);